name: Deploy and Merge Pipeline

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy-to-test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    outputs:
      deployment_status: ${{ steps.deploy.outputs.status }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          export_default_credentials: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Add project directory to PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run tests
        run: pytest

      - name: Deploy to Google App Engine Test
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          promote: false
          version: test

  merge-to-main:
    needs: deploy-to-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && needs.deploy-to-test.outputs.deployment_status == 'success'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge branches into master
        run: |
          BRANCHES=$(git branch -r | grep -v '\->' | grep -v 'main' | sed 's/origin\///')
          for branch in $BRANCHES; do
            CURRENT_BRANCH=$(git branch --show-current)
            if [ "$CURRENT_BRANCH" != "main" ]; then
              git checkout main
            fi
            git pull origin main
            if git merge --no-ff --allow-unrelated-histories origin/$branch -m "Merge branch '$branch' into main"; then
              echo "Merge successful for branch $branch"
              git push origin main
            else
              echo "Merge conflict or error occurred for branch $branch. Skipping..."
              git merge --abort
            fi
          done

  deploy-to-prod:
    needs: merge-to-main
    runs-on: ubuntu-latest
    if: success()
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          export_default_credentials: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Add project directory to PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Deploy to Google App Engine Production
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          promote: true
          version: prod
