name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3'  # Use the version you need

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run tests (Optional)
    - name: Run tests
      run: |
        pytest

    # Step 5: Authenticate to Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.4.0  # Use the latest version
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}  # Add your service account key in GitHub secrets

    # Step 6: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      run: |
        echo "Setting up Google Cloud SDK"
        echo ${{ secrets.GOOGLE_PROJECT_ID }} > project_id.txt
        gcloud config set project $(cat project_id.txt)

    # Step 7: Deploy to App Engine
    - name: Deploy to App Engine
      run: gcloud app deploy app.yaml --quiet
