name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
        export_default_credentials: true

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3'  # Use the version you need

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Add project directory to PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    # Step 4: Run tests (Optional)
    - name: Run tests
      run: |
        pytest

    # Step 7: Deploy to App Engine
    - name: Deploy to Google App Engine
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app.yaml
        project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
        credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
        promote: true
        version: v1
